yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),

]

yatube/yatube/urls.py
# yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
]

yatube/posts/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField()
    description = models.TextField(max_length=200)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True, null=True,
        on_delete=models.DO_NOTHING,
        related_name='group',
    )

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group


def index(request):
    posts = Post.objects.select_related('group').order_by('-pub_date')[:10]
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!doctype html>
<html>

<head>
{% include 'includes/header.html' %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>

<body>

    <main>
        <div class="container">
            <h1>{% block header %}{% endblock %}</h1>
            {% block content %}
            <!-- Содержимое страницы -->
            {% endblock %}
        </div>
    </main>
    {% include 'includes/footer.html' %}
</body>

</html>

yatube/templates/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="footer-copyright text-center py-3">© 2020 Copyright
        <p><span style="color:red">Ya</span>tube</p>
      </div>
</footer>

yatube/templates/includes/header.html
<div id="top-of-site">
{#  <img src="static/img/logo.png"  width="30" height="30" alt="Yatube" />#}
    <meta name="theme-color" content="#ffffff">
    <meta name="msapplication-TileColor" content="#000">
{#  <div id="site-name">Yatube</div>#}
    {% load static %}
  <div id="site-name"></div>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href='{% url 'posts:index' %}'>
{#            <img src="static/img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">#}
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>
</div>

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}Записи сообщества {{ group }}  Yatube{% endblock %}
{% block header %}Записи сообщества {{ group }}  Yatube{% endblock %}
{% block content %}
    <h1>{{ group }}</h1>
    <p>{{ group.description }}</p>
    {% for post in posts %}
    <h3>Автор: {{ post.author.get_full_name }}, Дата публикации: {{ post.pub_date|date:"d M Y" }}</h3>
    <p>{{ post.text|linebreaksbr }}</p>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}

{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}

    {% for post in posts %}
    <ul>
        <li>Автор: {{ post.author.get_full_name }}</li>
        <li>Дата публикации: {{ post.pub_date|date:"d M Y" }}</li>
    </ul>

    <p>{{ post.text|linebreaksbr }}</p>
        {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
        {% endif %}

    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}


{% endblock %} 